# Generated by Django 3.0.5 on 2020-04-27 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmoment',
            name='screenshot_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='savedmoment',
            unique_together={('owner', 'url')},
        ),
        migrations.RemoveField(
            model_name='savedmoment',
            name='screenshot_url',
        ),
    ]
