# Generated by Django 3.0.5 on 2020-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pup', '0002_auto_20200427_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmoment',
            name='image_encoded',
            field=models.TextField(blank=True),
        ),
    ]
