# Generated by Django 3.0.8 on 2020-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pup', '0002_auto_20200427_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmoment',
            name='url_type',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter')], max_length=16),
        ),
    ]
